# -*- mode: ruby -*-
# vi: set ft=ruby :

VICTIM_BOX_NAME = ENV.fetch("VICTIM_BOX_NAME", "victim-master")
ROGUE_BOX_NAME = ENV.fetch("ROGUE_BOX_NAME", "rogue-master")
BOX_SYS = ENV.fetch("BOX_SYS", "ubuntu/trusty64")
VICTIM_IP = ENV.fetch("VICTIM_IP", "192.168.34.9")
ROGUE_IP = ENV.fetch("VICTIM_IP", "192.168.34.42")
BOX_NOPROXY = ENV.fetch("BOX_NOPROXY", "localhost,127.0.0.1, 192.168.56.*, 192.168.34.*")
BOX_PROXY = ENV.fetch("BOX_PROXY", "<insert proxy here>")
BOX_MEM = ENV.fetch("BOX_MEM", "512")
BOX_CPUS = ENV.fetch("BOX_CPUS", "1")
VAGRANTFILE_API_VERSION = "2"

REQUIRED_PLUGINS = %w(vagrant-vbguest vagrant-proxyconf)
# install required plugins
plugins_to_install = REQUIRED_PLUGINS.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing required plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	# config for the victim box
	config.vm.define :victim do |victim|
    victim.vm.box = BOX_SYS
    victim.vm.hostname = VICTIM_BOX_NAME

    config.vm.provision :shell, :path => "victim_provisioning.sh"

    # set proxy
    if Vagrant.has_plugin?("vagrant-proxyconf")
      config.proxy.http     = BOX_PROXY
      config.proxy.https    = BOX_PROXY
      config.proxy.no_proxy = BOX_NOPROXY
    end

    # victim port
    victim.vm.network "private_network", ip: VICTIM_IP
    victim.vm.network :forwarded_port, guest: 31337, host: 31337

    victim.vm.provider "virtualbox" do |v|
      v.memory = BOX_MEM
      v.cpus = BOX_CPUS
    end
  end

  # config for the rogue box
  	config.vm.define :rogue do |rogue|
      rogue.vm.box = BOX_SYS
      rogue.vm.hostname = ROGUE_BOX_NAME

      config.vm.provision :shell, :path => "rogue_provisioning.sh"

      # set proxy
      if Vagrant.has_plugin?("vagrant-proxyconf")
        config.proxy.http     = BOX_PROXY
        config.proxy.https    = BOX_PROXY
        config.proxy.no_proxy = BOX_NOPROXY
      end

      # rogue port
      rogue.vm.network "private_network", ip: ROGUE_IP
      rogue.vm.network :forwarded_port, guest: 1099, host: 1099

      rogue.vm.provider "virtualbox" do |v|
        v.memory = BOX_MEM
        v.cpus = BOX_CPUS
      end
    end

end
